version: "3"

services:
  nuxt:
    build: ./
    container_name: frontend-website
    restart: always
    ports:
      - "80:80"
    command:
      "yarn run build & yarn run start"

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=negar.in
