#!/bin/bash

NC='\033[0m'        # No Color
BGreen='\033[1;32m' # Green

if [ -z "$1" ]; then
    printf "${BGreen}backedn${NC}  → backend command\n"
    printf "${BGreen}artisan${NC}  → Laravel artisan command\n"
    printf "${BGreen}composer${NC} → composer command\n"
    printf "\n"
    printf "${BGreen}frontend${NC} → frontend command\n"
    printf "${BGreen}yarn${NC}     → yarn command\n"
    printf "\n"
    printf "${BGreen}database${NC} → database command\n"
    printf "${BGreen}psql${NC}     → PSQL command\n"
    printf "\n"
    printf "${BGreen}cert${NC}     → Generate self-signed certificate\n"
    exit 1
fi

cd "scripts"

# Backend scripts
if [ $1 = "backend" ]; then
    eval "./backend.sh \"${@:2}\""
    exit 1
elif [ $1 = "artisan" ]; then
    eval "./artisan.sh \"${@:2}\""
    exit 1
elif [ $1 = "tinker" ]; then
    eval "./tinker.sh"
    exit;
elif [ $1 = "composer" ]; then
    eval "./composer.sh \"${@:2}\""
    exit 1
fi

# Frontend scripts
if [ $1 = "frontend" ]; then
    eval "./frontend.sh \"${@:2}\""
    exit 1
elif [ $1 = "yarn" ]; then
    eval "./yarn.sh \"${@:2}"\"
    exit 1
fi

# Database scripts
if [ $1 = "database" ]; then
    eval "./database.sh \"${@:2}\""
    exit 1
elif [ $1 = "psql" ]; then
    eval "./psql.sh \"${@:2}"\"
    exit 1
fi

# Cert
if [ $1 = "cert" ]; then
    eval "./cert.sh \"${@:2}\""
    exit 1
fi
