version: "3.2"

services:
  admin:
    image: admin:${ADMIN_TAG}
    build:
      context: ./admin
      dockerfile: ../deploy/dev/admin/Dockerfile
      args:
        - NODE_VERSION=${NODE_VERSION}
    container_name: coleus-admin
    restart: unless-stopped
    ports:
      - 5000:5000
    working_dir: /var/www/admin
    command: "serve -s build"
    networks:
      - backend-network

  backend:
    image: backend:${BACKEND_TAG}
    build:
      context: ./backend
      args:
        FPM_VERSION: ${FPM_VERSION}
        BACKEND_PORT: ${BACKEND_PORT}
      dockerfile: ../deploy/dev/backend/Dockerfile
    container_name: coleus-dev-backend
    restart: unless-stopped
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    working_dir: /var/www/backend
    depends_on:
      - database
      - cache
    volumes:
      - ./backend:/var/www/backend
      - ./deploy/dev/backend/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./deploy/dev/backend/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
    networks:
      - backend-network

  database:
    image: postgres:${PGSQL_VERSION}
    container_name: coleus-dev-database
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./deploy/dev/database/data:/var/lib/postgresql/data
    networks:
      - backend-network

  graphql:
    image: hasura/graphql-engine:v1.2.1.cli-migrations-v2
    container_name: coleus-dev-graphql
    ports:
      - 8180:8180
    depends_on:
      - database
    restart: unless-stopped
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@database:5432/coleus
      HASURA_GRAPHQL_ENABLE_CONSOLE: "${GRAPHQL_ENABLE_CONSOLE}"
      HASURA_GRAPHQL_ENABLE_ALLOWLIST: "${GRAPHQL_ENABLE_ALLOWLIST}"
      GRAPHQL_BACKEND_ENDPOINT: "${GRAPHQL_BACKEND_ENDPOINT}"
    volumes:
      - ./graphql/metadata:/hasura-metadata
      - ${PWD}/graphql/config.yaml:/config.yaml
    networks:
      - backend-network

  proxy:
    image: nginx:${NGINX_VERSION}
    container_name: coleus-dev-proxy
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/backend
      - ./deploy/dev/nginx/conf.d/:/etc/nginx/conf.d/
      - ./deploy/dev/nginx/log/:/var/log/nginx/
    depends_on:
      - backend
    networks:
      - backend-network

  cache:
    image: redis:${REDIS_VERSION}
    container_name: coleus-dev-cache
    command: ["redis-server"]
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./deploy/dev/redis-data:/data
    networks:
      - backend-network

  search:
    image: valeriansaliou/sonic:${SONIC_VERSION}
    container_name: coleus-dev-search
    restart: unless-stopped
    volumes:
      - ./deploy/dev/sonic/config.cfg:/etc/sonic.cfg
      - ./deploy/dev/sonic/store/:/var/lib/sonic/store/
    ports:
      - 1491:1491
    networks:
      - backend-network

  storage:
    image: minio/minio
    container_name: coleus-dev-storage
    restart: unless-stopped
    volumes:
      - ./storage:/data
      - ./deploy/dev/minio:/root/.minio
    ports:
      - 9001:9000
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_DOMAIN=${MINIO_PUBLIC_URL}
      - MINIO_BROWSER=${MINIO_BROWSER}
      - MINIO_REGION=us-east-1
    command: ["server", "/data"]
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # broker:
  #   image: rabbitmq:3.8.2-management-alpine
  #   container_name: coleus-dev-broker
  #   restart: unless-stopped
  #   volumes:
  #     - ./rabbitmq/etc/:/etc/rabbitmq/
  #     - ./rabbitmq/data/:/var/lib/rabbitmq/mnesia/
  #     - ./rabbitmq/logs/:/var/log/rabbitmq/
  #   environment:
  #     RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
  #     RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
  #     RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
  #   networks:
  #     - backend-network

  image:
    image: darthsim/imgproxy:latest
    container_name: coleus-dev-image
    restart: unless-stopped
    environment:
      IMGPROXY_KEY: ${IMGPROXY_KEY}
      IMGPROXY_SALT: ${IMGPROXY_SALT}
      IMGPROXY_SIGNATURE_SIZE: ${IMGPROXY_SIGNATURE_SIZE}
      IMGPROXY_QUALITY: ${IMGPROXY_QUALITY}
      IMGPROXY_GZIP_COMPRESSION: ${IMGPROXY_GZIP_COMPRESSION}
      IMGPROXY_JPEG_PROGRESSIVE: ${IMGPROXY_JPEG_PROGRESSIVE}
      IMGPROXY_SENTRY_DSN: ${IMGPROXY_SENTRY_DSN}
      IMGPROXY_SENTRY_ENVIRONMENT: ${IMGPROXY_SENTRY_ENVIRONMENT}
      IMGPROXY_SENTRY_RELEASE: ${IMGPROXY_SENTRY_RELEASE}
      IMGPROXY_USE_S3: ${IMGPROXY_USE_S3}
      IMGPROXY_LOCAL_FILESYSTEM_ROOT: /opt
      IMGPROXY_S3_ENDPOINT: http://storage:9000
      AWS_ACCESS_KEY_ID: ${MINIO_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${MINIO_SECRET_KEY}
      AWS_REGION: us-east-1
    ports:
      - 8080:8080
    volumes:
      - ./storage:/opt
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  data:
  redis-data:
  storage:
  minio:
