version: '2'

services:
  reverseproxy:
    image: reverseproxy
    ports:
      - 8080:8080
      - 8081:8081
    restart: always

  negarin_gql:
    depends_on:
      - reverseproxy
    image: nginx:alpine
    restart: always

  negarin_client:
    depends_on:
      - reverseproxy
    image: httpd:alpine
    restart: always
