query Pages($page: bigint) {
  pages(where: { id: { _eq: $page } }) {
    id
    title
    page {
      title
    }
    blocks(order_by: { order: asc }) {
      id
      content
      type
    }
    book {
      title
      book_users {
        user {
          name
          username
        }
      }
    }
  }
}
