query FetchUserByUsername($username: String) {
  users(where: {username: {_eq: $username}}) {
    username
    medium
    name
    original
    photo_url
    placeholder
    small
    status
    sticky
    thumbnail
    website
    xsmall
    books(order_by: {order: desc}) {
      medium
      order
      original
      placeholder
      slug
      small
      status
      sticky
      thumbnail
      title
      website
      xsmall
    }
  }
}
