query FetchUserByUsername($username: String) {
  users(where: {username: {_ilike: $username}}) {
    username
    medium
    name
    original
    photo_url
    placeholder
    small
    status
    sticky
    thumbnail
    website
    xsmall
    book_users {
      book {
        medium
        order
        original
        placeholder
        slug
        small
        status
        sticky
        thumbnail
        title
        website
        xsmall
      }
    }
  }
}
