query FetchUsers {
  users(sticky: true) {
    data {
        id
        name
        xsmall
        small
        photo_url
        placeholder
        username
        bio
        books {
            title
            slug
        }
    }
  }
}
