version: "3"

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: ../deploy/frontend/Dockerfile
    container_name: negarin-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    working_dir: /var/www/frontend
    networks:
      - frontend-network

  backend:
    build:
      context: ../backend
      dockerfile: ../deploy/backend/Dockerfile
    container_name: negarin-backend
    restart: unless-stopped
    ports:
      - "9000:9000"
    tty: true
    working_dir: /var/www/backend
    volumes:
      - ../backend:/var/www/backend
      - ../deploy/backend/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - backend-network

  database:
    image: postgres:${PGSQL_VERSION}
    container_name: negarin-database
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data
    networks:
      - backend-network

  nginx:
    image: nginx:1.17.7-alpine
    container_name: negarin-nginx
    ports:
      - "80:80"
      - "443:443"
    tty: true
    restart: unless-stopped
    volumes:
      - ./nginx/certs/:/etc/ssl/certs/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ../backend:/var/www/backend
      - ../frontend:/var/www/frontend
      - ./nginx/log/:/var/log/nginx/
    depends_on:
      - frontend
      - backend
    networks:
      - backend-network
      - frontend-network

networks:
  # default:
  #   external:
  #     name: proxy-nginx
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge

volumes:
  dbdata:
