version: "3"

services:
  # frontend:
  #   build:
  #     context: ../frontend
  #     dockerfile: ../deploy/frontend/Dockerfile
  #     args:
  #       - NODE_VERSION=${NODE_VERSION}
  #   container_name: negarin-frontend
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   working_dir: /var/www/frontend
  #   networks:
  #     - frontend-network

  backend:
    build:
      context: ../backend
      args:
        FPM_VERSION: ${FPM_VERSION}
      dockerfile: ../deploy/backend/Dockerfile.dev
    container_name: negarin-backend
    restart: unless-stopped
    ports:
      - "9000:9000"
    tty: true
    working_dir: /var/www/backend
    depends_on:
      - database
      - redis
    volumes:
      - ../backend:/var/www/backend
      - ../deploy/backend/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ../deploy/backend/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
    networks:
      - backend-network

  database:
    image: postgres:${PGSQL_VERSION}
    container_name: negarin-database
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data
    networks:
      - backend-network

  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-beta.6
    container_name: negarin-graphql-engine
    ports:
      - "8080:8080"
    depends_on:
      - "database"
    restart: unless-stopped
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@database:5432/negarin
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
    networks:
      - backend-network

  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: negarin-nginx
    ports:
      - "80:80"
      - "443:443"
    tty: true
    restart: unless-stopped
    volumes:
      - ./nginx/certs/:/etc/ssl/certs/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ../backend:/var/www/backend
      - ./nginx/log/:/var/log/nginx/
    depends_on:
      - backend
    networks:
      - backend-network

  redis:
    image: redis:${REDIS_VERSION}
    container_name: negarin-redis
    command: ["redis-server"]
    hostname: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - backend-network

  elasticsearch:
    image: elasticsearch:7.5.2
    container_name: negarin-elasticsearch
    hostname: elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - backend-network

  minio:
    image: minio/minio
    container_name: negarin-minio
    hostname: minio
    restart: unless-stopped
    volumes:
      - ../storage:/data
    ports:
      - "9001:9000"
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    command: server /data
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  backend-network:
    driver: bridge

volumes:
  data:
  redis-data:
  storage:
