query FetchTrending {
  trending {
    data {
      id
      title
      book {
        title
        slug
        collaborators {
          name
          username
          thumbnail
          photo_url
          placeholder
        }
      }
    }
  }
}
