mutation RegisterUser($name: String!, $email: String!, $password: String!, $password_confirmation: String!) {
  register(name: $name, email: $email, password: $password, password_confirmation: $password_confirmation) {
    id
  }
}
